### ISSUE TITLE
关于密钥的处理方案

### ISSUE THREAD

**Issue by anycodes** [DevDengChao/refresh-cdn-cache#6]
![image](https://user-images.githubusercontent.com/21079031/168334542-4b2a1c6c-803e-490f-b022-f418d4d7f90b.png)

1. 优先使用项目的密钥信息（在inputs参数中，参考https://docs.serverless-devs.com/sdm/serverless_package_model/package_model#%E6%8F%92%E4%BB%B6%E6%A8%A1%E5%9E%8B%E8%A7%84%E8%8C%83）
![image](https://user-images.githubusercontent.com/21079031/168334805-c636cac5-fbb1-422a-8edd-002d559a2e27.png)

3. 也可以通过指定密钥使用指定的密钥信息

**Comment by DevDengChao** [comment]
因为一开始的时候我考虑的是 FC 相关的操作权限与 CDN 相关的操作权限不在同一个 RAM 账户下的情况, 所以优先实现了现在这种指明 accessKeyId 与 accessKeySecret 的方式.

现在基本功能已经实现了, 可以考虑默认加载当前 access 对应的密钥了, 计划下周实现这个功能.

**Comment by DevDengChao** [comment]
该特性已实现, 详见 [readme 中的 "密钥加载优先级" 章节](https://github.com/DevDengChao/refresh-cdn-cache#%E5%AF%86%E9%92%A5%E5%8A%A0%E8%BD%BD%E4%BC%98%E5%85%88%E7%BA%A7).
